USE Vaktbok_2;

CREATE TABLE IF NOT EXISTS Employee(
	Id VARCHAR(36) PRIMARY KEY,
	Name VARCHAR(100) UNIQUE NOT NULL,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ShiftCode(
    Id VARCHAR(36) PRIMARY KEY,
    Code VARCHAR(10) UNIQUE NOT NULL,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ShiftRemark(
    Id VARCHAR(36) PRIMARY KEY,
    Remark VARCHAR(10) NOT NULL,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Workday (
    Id VARCHAR(36) PRIMARY KEY,
    Day SMALLINT NOT NULL,
    Week SMALLINT NOT NULL,
    Year SMALLINT NOT NULL,
    Date DATETIME NOT NULL,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FilePath (
    Id VARCHAR(36) PRIMARY KEY,
    Path VARCHAR(100),  
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);      

CREATE TABLE IF NOT EXISTS Shift(
    Id VARCHAR(36) PRIMARY KEY,
    EmployeeId VARCHAR(36) NOT NULL,
    WorkdayId VARCHAR(36) NOT NULL,
    ShiftCodeId VARCHAR(36),
    ShiftRemarkId VARCHAR(36),
    FilePathId VARCHAR(36),
    
    Time VARCHAR(15),
    
    FOREIGN KEY (EmployeeId) REFERENCES Employee(Id)
		ON DELETE CASCADE,
    FOREIGN KEY (WorkdayId) REFERENCES Workday(Id)
        ON DELETE RESTRICT,
    FOREIGN KEY (ShiftCodeId) REFERENCES ShiftCode(Id)
        ON DELETE RESTRICT,
    FOREIGN KEY (ShiftRemarkId) REFERENCES ShiftRemark(Id)
        ON DELETE RESTRICT,
    FOREIGN KEY (FilePathId) REFERENCES FilePath(Id)
        ON DELETE RESTRICT,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)