USE Vaktbok_2;

CREATE TABLE IF NOT EXISTS Employee(
	IdBinary BINARY(16) PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ShiftCode(
	IdBinary BINARY(16) PRIMARY KEY,
    Code VARCHAR(10) NOT NULL,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ShiftRemark(
	IdBinary BINARY(16) PRIMARY KEY,
    Remark VARCHAR(10) NOT NULL,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Workday (
	IdBinary BINARY(16) PRIMARY KEY,
    Day SMALLINT NOT NULL,
    Week SMALLINT NOT NULL,
    Year SMALLINT NOT NULL,
    Date DATETIME NOT NULL,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Shift(
	IdBinary BINARY(16) PRIMARY KEY,
    EmployeeId BINARY(16) NOT NULL,
    WorkdayId BINARY(16) NOT NULL,
    ShiftCodeId BINARY(16),
    ShiftRemarkId Binary(16),
    
    Time VARCHAR(15),
    
    FOREIGN KEY (EmployeeId) REFERENCES Employee(IdBinary)
		ON DELETE CASCADE,
    FOREIGN KEY (WorkdayId) REFERENCES Workday(IdBinary)
        ON DELETE RESTRICT,
    FOREIGN KEY (ShiftCodeId) REFERENCES ShiftCode(IdBinary)
        ON DELETE RESTRICT,
    FOREIGN KEY (ShiftRemarkId) REFERENCES ShiftRemark(IdBinary)
        ON DELETE RESTRICT,
    
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)